export class Perfil {
  constructor(
    public id: number = null,
    public descricao: string = '',
    public cadastros: string = 'N',
    public cadastros_servico: string = 'N',
    public cadastros_cliente: string = 'N',
    public cadastros_contrato: string = 'N',
    public cadastros_contrato_cliente: string = 'N',
    public cadastros_contrato_fornecedor: string = 'N',
    public cadastros_documento_cliente: string = 'N',
    public cadastros_documento_fornecedor: string = 'N',
    public cadastros_fornecedor: string = 'N',
    public cadastros_residuo: string = 'N',
    public cadastros_residuo_acondicionamento: string = 'N',
    public cadastros_residuo_classe_residuo: string = 'N',
    public cadastros_residuo_residuos: string = 'N',
    public cadastros_residuo_tipo_tratamento: string = 'N',
    public cadastros_residuo_tipo_residuo: string = 'N',
    public cadastros_residuo_unidade: string = 'N',
    public cadastros_equipamento: string = 'N',
    public processos: string = 'N',
    public processos_manifesto: string = 'N',
    public processos_monitor_documento: string = 'N',
    public processos_apuracao_locacao: string = 'N',
    public processos_pesagem: string = 'N',
    public relatorios: string = 'N',
    public relatorios_gerencial: string = 'N',
    public relatorios_gerencia_cliente: string = 'N',
    public relatorios_gerencia_ambiente_verde: string = 'N',
    public relatorios_controle_pesagem: string = 'N',
    public relatorios_mapa_residuos: string = 'N',
    public relatorios_controle_pagamento: string = 'N',
    public relatorios_consolidado_periodo: string = 'N',
    public relatorios_protocolo_entrega: string = 'N',
    public aclcontrol_adicionar_usuario: string = 'N',
    public aclcontrol_redefinir_senha: string = 'N'
  ) {}
}
